### ISSUE TITLE
Help needed: compile latex document with `graphviz` package

### ISSUE THREAD

**Issue by Jeff-Tian** [dante-ev/latex-action#2]
Hello I met an issue regarding compiling latex document with this action when using `graphviz` package, I created a PR #1 to take the advantage of `code diff`. Could you please help investigate where is wrong? Thanks in advance!

**Comment by drupol** [comment]
The README says:

```
extra_system_packages

The extra packages to be installed by apt-get separated by space.
```

Does this fix your issue?

**Comment by Jeff-Tian** [comment]
Thanks @drupol !
