### ISSUE TITLE
Caching?

### ISSUE THREAD

**Issue by rugk** [dante-ev/latex-action#6]
Could it integrate some [caching](https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows) of LaTeX, bibtex/biber etc. intermeditary files ([best known from .gitignores](https://github.com/github/gitignore/blob/master/TeX.gitignore)) to speed up the build?

Or do we have to add that manually, if we want?

**Comment by rugk** [comment]
BTW, I've done it like this, now:

```
      - name: Cache
        uses: actions/cache@v2.1.3
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: |
            *.aux
            *.lof
            *.log
            *.lot
            *.fls
            *.out
            *.toc
            *.fmt
            *.fot
            *.cb
            *.cb2
            .*.lb
            *.bbl
            *.bcf
            *.blg
            *-blx.aux
            *-blx.bib
            *.run.xml
  ```
  
 Dunno, if this is the recommend approach, but it seems to work.

**Comment by rugk** [comment]
To periodically re-create the cache (at least once a day), I've set the date as the key now. I guess this is better, especially as the caching for small documents only speeds up the build for some seconds:

```yaml
      # https://github.com/actions/cache#creating-a-cache-key
      # http://man7.org/linux/man-pages/man1/date.1.html
      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash

      - name: Cache
        uses: actions/cache@v2.1.3
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: |
            *.aux
            *.lof
            *.lot
            *.fls
            *.out
            *.toc
            *.fmt
            *.fot
            *.cb
            *.cb2
            .*.lb
            *.bbl
            *.bcf
            *.blg
            *-blx.aux
            *-blx.bib
            *.run.xml
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}
```

**Comment by koppor** [comment]
I am not sure about caching of the files. Sometimes when doing changes with huge impact, the .tex document does not compile any more. - Such as adding/removing hyperref, switching from pdflatex to lualatex, ...

I am not sure about the target group of this action. Do the people know what they are doing?

Maybe, it's as easy as adding these code snippets to the `README.md`. Could you submit a PR?
