### ISSUE TITLE
Building step takes reeally long…

### ISSUE THREAD

**Issue by rugk** [dante-ev/latex-action#7]
GitHub's building step for the template takes really long… is not this “just” a download?

6 minutes is not special:
![grafik](https://user-images.githubusercontent.com/11966684/105777500-c6b73680-5f6a-11eb-9d37-83ee62e08737.png)

Can one speed this up?

**Comment by splitt3r** [comment]
I think the Docker Image latest tag in https://github.com/dante-ev/latex-action/blob/master/Dockerfile#L1 is making this Action slow. Maybe using some tag like v0.0.1 would make the GitHub Action caching possible / faster + using GitHub Container Registry.

**Comment by rugk** [comment]
I guess PR https://github.com/dante-ev/latex-action/pull/4, which uses the internal GitHub container registry, may already make a difference, does not it?

The latest container tag won't change as fast…

**Comment by tomOdy-DigitalInterruption** [comment]
I'm also very interested in seeing PR dante-ev/latex-action#4 merged. Build time is irritatingly long

**Comment by claudiacauli** [comment]
Agree with all the other comments. The build time was much faster (~2 minutes) months ago. 
It takes, on average, 6-7 minutes now.

**Comment by rugk** [comment]
Could you make a release tag for that change to be included? So one can reference that like `dante-ev/latex-action@v0.3` or so?

ALso maybe make  a stable version 1.0.0, I see no reason to continue to use [0-based versioning](https://0ver.org/).

**Comment by koppor** [comment]
I released `2021-A` today. I decided to follow the versioning scheme of the underlying docker image. That, in turn, uses a variant of [CalVer](https://calver.org/): First, the texlive year, then the release within that year. Numbered starting with a letter, to avoid confustion with month.

You can use `@latest` to always use the latest release or `@edge` for the twice-monthly build version.

Full changelog: https://github.com/dante-ev/latex-action/blob/edge/CHANGELOG.md

**Comment by koppor** [comment]
In general, this image opts for being larger and thereby gaining full compatibility.

The other option would be to build a custom `Dockerfile` for each document. This is somehow outlined in https://github.com/reitzig/texlive-docker (linked from https://github.com/dante-ev/docker-texlive#alternatives), but I found it too complicated to create and explain. 😇
